data_leakage_prevention:
  strategy: within_subject

intra_test_train_split:
  train_ratio: 0.8
  split_method: start
  split_seed: 42

feature_transformation:
  transformations:
    - "Dummy (+1)"

output_format: ml
