status = error

appender.file.type = File
appender.file.name = FILE
# entrypoint.sh --> export LOG_FILE_PATH="/opt/bitnami/spark/logs/spark-driver-$(date +%Y-%m-%d_%H-%M).log"
appender.file.fileName = ${env:LOG_FILE_PATH}
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}: %m%n

# logging levels: "ALL", "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "OFF"
# anything below info will make a f*king massive log file (i got one of 56GB) so we set it to warn unless testing for something specific
rootLogger.level = WARN  
rootLogger.appenderRefs = file
rootLogger.appenderRef.file.ref = FILE

