#!/usr/bin/env python3
"""Generate all AD vs cntrl HPC YAML configs matching configs_ftd_vs_cntrl_HPC styling."""

from pathlib import Path

ROOT = Path(__file__).parent
HPC_BASE = "/scratch/ans9868/ds004504-download"

ALZ_SUBS  = [f"sub-{i:03d}" for i in range(1, 37)]
CNTRL_SUBS = [f"sub-{i:03d}" for i in range(37, 66)]

def sub_path(s):
    return f"{HPC_BASE}/{s}/eeg/{s}_task-eyesclosed_eeg.set"

ALZ_PATHS   = [sub_path(s) for s in ALZ_SUBS]
CNTRL_PATHS = [sub_path(s) for s in CNTRL_SUBS]

# ── Fold lists (generated by mac config with seed=42) ──────────────────────────

L6_FOLDS_RAW = [
    ["sub-024","sub-004","sub-028","sub-039","sub-057","sub-060"],
    ["sub-018","sub-035","sub-027","sub-051","sub-058","sub-040"],
    ["sub-018","sub-013","sub-007","sub-060","sub-054","sub-048"],
    ["sub-016","sub-004","sub-008","sub-065","sub-061","sub-038"],
    ["sub-026","sub-006","sub-027","sub-063","sub-049","sub-062"],
    ["sub-014","sub-026","sub-007","sub-038","sub-052","sub-041"],
    ["sub-027","sub-032","sub-014","sub-062","sub-047","sub-045"],
    ["sub-017","sub-007","sub-028","sub-049","sub-043","sub-046"],
    ["sub-032","sub-016","sub-006","sub-055","sub-039","sub-046"],
    ["sub-015","sub-031","sub-029","sub-056","sub-044","sub-043"],
    ["sub-036","sub-007","sub-029","sub-058","sub-056","sub-064"],
    ["sub-010","sub-021","sub-028","sub-038","sub-041","sub-052"],
    ["sub-015","sub-036","sub-024","sub-052","sub-059","sub-039"],
    ["sub-020","sub-004","sub-035","sub-037","sub-045","sub-053"],
    ["sub-034","sub-010","sub-008","sub-037","sub-060","sub-043"],
    ["sub-010","sub-034","sub-030","sub-054","sub-053","sub-040"],
    ["sub-015","sub-034","sub-024","sub-041","sub-058","sub-045"],
    ["sub-004","sub-035","sub-028","sub-049","sub-057","sub-041"],
    ["sub-006","sub-032","sub-018","sub-041","sub-048","sub-049"],
    ["sub-024","sub-022","sub-023","sub-039","sub-040","sub-046"],
    ["sub-032","sub-013","sub-018","sub-065","sub-058","sub-044"],
    ["sub-009","sub-029","sub-026","sub-044","sub-065","sub-039"],
    ["sub-026","sub-016","sub-005","sub-053","sub-045","sub-059"],
    ["sub-030","sub-016","sub-001","sub-049","sub-055","sub-056"],
    ["sub-005","sub-004","sub-021","sub-058","sub-039","sub-049"],
    ["sub-036","sub-018","sub-007","sub-039","sub-055","sub-040"],
    ["sub-027","sub-006","sub-011","sub-052","sub-047","sub-049"],
    ["sub-001","sub-011","sub-006","sub-064","sub-059","sub-050"],
    ["sub-025","sub-010","sub-018","sub-053","sub-062","sub-041"],
    ["sub-035","sub-010","sub-028","sub-060","sub-049","sub-051"],
    ["sub-013","sub-029","sub-001","sub-045","sub-053","sub-040"],
    ["sub-024","sub-005","sub-023","sub-054","sub-057","sub-058"],
    ["sub-011","sub-004","sub-023","sub-038","sub-064","sub-043"],
    ["sub-013","sub-019","sub-012","sub-046","sub-063","sub-058"],
    ["sub-022","sub-023","sub-011","sub-064","sub-065","sub-043"],
    ["sub-019","sub-011","sub-002","sub-062","sub-041","sub-063"],
    ["sub-032","sub-029","sub-009","sub-046","sub-050","sub-051"],
    ["sub-012","sub-015","sub-024","sub-058","sub-039","sub-057"],
    ["sub-033","sub-035","sub-001","sub-038","sub-040","sub-061"],
    ["sub-026","sub-014","sub-007","sub-038","sub-042","sub-060"],
    ["sub-028","sub-034","sub-012","sub-049","sub-050","sub-041"],
    ["sub-009","sub-011","sub-006","sub-040","sub-064","sub-055"],
    ["sub-028","sub-032","sub-025","sub-060","sub-061","sub-042"],
    ["sub-026","sub-030","sub-003","sub-052","sub-063","sub-040"],
    ["sub-034","sub-005","sub-011","sub-064","sub-054","sub-045"],
    ["sub-018","sub-035","sub-033","sub-041","sub-051","sub-055"],
    ["sub-027","sub-025","sub-005","sub-054","sub-041","sub-063"],
    ["sub-026","sub-016","sub-029","sub-037","sub-058","sub-060"],
    ["sub-030","sub-010","sub-036","sub-043","sub-046","sub-052"],
    ["sub-028","sub-032","sub-031","sub-040","sub-048","sub-047"],
]

L2_FOLDS_RAW = [
    ["sub-004","sub-059"],
    ["sub-024","sub-049"],
    ["sub-016","sub-061"],
    ["sub-004","sub-057"],
    ["sub-008","sub-039"],
    ["sub-019","sub-065"],
    ["sub-027","sub-059"],
    ["sub-026","sub-059"],
    ["sub-019","sub-040"],
    ["sub-031","sub-050"],
    ["sub-019","sub-047"],
    ["sub-007","sub-063"],
    ["sub-029","sub-055"],
    ["sub-015","sub-060"],
    ["sub-020","sub-049"],
    ["sub-017","sub-043"],
    ["sub-004","sub-053"],
    ["sub-032","sub-038"],
    ["sub-031","sub-061"],
    ["sub-010","sub-055"],
    ["sub-006","sub-058"],
    ["sub-026","sub-047"],
    ["sub-003","sub-065"],
    ["sub-017","sub-062"],
    ["sub-025","sub-059"],
    ["sub-028","sub-042"],
    ["sub-014","sub-050"],
    ["sub-018","sub-038"],
    ["sub-020","sub-041"],
    ["sub-027","sub-056"],
    ["sub-034","sub-058"],
    ["sub-014","sub-065"],
    ["sub-015","sub-046"],
    ["sub-033","sub-047"],
    ["sub-003","sub-050"],
    ["sub-029","sub-042"],
    ["sub-017","sub-040"],
    ["sub-025","sub-050"],
    ["sub-012","sub-043"],
    ["sub-021","sub-056"],
    ["sub-034","sub-049"],
    ["sub-006","sub-061"],
    ["sub-023","sub-057"],
    ["sub-004","sub-046"],
    ["sub-028","sub-061"],
    ["sub-016","sub-060"],
    ["sub-031","sub-048"],
    ["sub-033","sub-045"],
    ["sub-009","sub-056"],
    ["sub-023","sub-041"],
]

L6_FOLDS  = [[sub_path(s) for s in fold] for fold in L6_FOLDS_RAW]
L2_FOLDS  = [[sub_path(s) for s in fold] for fold in L2_FOLDS_RAW]

# ── Template builders ──────────────────────────────────────────────────────────

SLURM = """\
  slurm_options:
    build: --time=00:15:00 --mem=12G --cpus-per-task=2 --account=torch_pr_60_general
    pyspark: --time=08:00:00 --mem=56G --cpus-per-task=12 --account=torch_pr_60_general
    ray: --time=08:00:00 --mem=56G --cpus-per-task=12 --account=torch_pr_60_general"""

PREPROCESSING = """\
preprocessing:
  bands:
    Delta:
    - 0.5
    - 4
    Theta:
    - 4
    - 8
    Alpha:
    - 8
    - 12
    Beta:
    - 12
    - 30
  window_size: 3.0
  sliding_window: 0.5
  reject_by_annotation: 'Yes'
  normalize_psd: 'Yes'
  use_epoch_rejection: 'Yes'
  epoch_rejection:
    reject: 800.0
    flat: 0.3
  extreme_datapoint_removal: null"""

FEATURE_EXTRACTION = """\
feature_extraction:
  method: welch
  features:
    per_channel_across_bands:
    - band_power
    - none
    per_channel_per_band:
    - relative_band_power
  show_intermediate_results: 'No'
  show_intermediate_counts: 'No'
  output_format: ml"""

FEATURE_TRANSFORM_ANOVA = """\
feature_transformation:
  transformations:
  - ANOVA F-test
  - MinMax scaler
  synthetic: None
  minmax_range:
  - -1.0
  - 1.0
  anova_label_column: Group
  anova_label_type: categorical
  anova_selection_mode: fwe
  anova_selection_threshold: 0.05"""

FEATURE_TRANSFORM_PCA = """\
feature_transformation:
  transformations:
  - Z-score standardization
  - PCA (retain 95% variance)
  synthetic: None"""

PYSPARK = """\
pyspark:
  master: 12
  driver_memory: 36
  executor_memory: 36
  executor_cores: 12
  shuffle_partitions: 24"""

RAY = """\
ray:
  search_strategies:
  - grid_search
  grid_search:
    models:
    - XGBoost
    - MLP (Neural Network)
    - KNN
    - SVM
    model_configs:
      XGBoost:
        use_default: false
        hyperparameters:
          n_estimators:
          - '100'
          max_depth:
          - '3'
          - '6'
          - '9'
          learning_rate:
          - '0.2'
          subsample:
          - '0.7'
      MLP (Neural Network):
        use_default: false
        hyperparameters:
          hidden_layer_sizes:
          - - 100
          - - 150
            - 50
          - - 200
            - 100
            - 50
          activation:
          - tanh
          alpha:
          - '0.1'
      KNN:
        use_default: false
        hyperparameters:
          n_neighbors:
          - 1
          - 7
          - 15
          weights:
          - uniform
          metric:
          - euclidean
      SVM:
        use_default: false
        hyperparameters:
          C:
          - '0.1'
          kernel:
          - linear
          - rbf
          - poly
          gamma:
          - auto
    max_concurrent_trials: 9
    cv_folds: 5
  metric: accuracy
  mode: max
  graph_data_visualization:
    save_prediction_outputs: 'Yes'
    best_models_graph: 'Yes'
    per_model_accross_hyperparameters_graph: 'Yes'
    per_model_per_hyperparameter_across_folds_graph: 'Yes'
    per_subject_analysis_graph: 'Yes'
    per_subject_top_n_models: 5
    per_subject_hyperparameter_analysis: 'Yes'
  resources:
    num_cpus: 12
    memory_gb: 42
    object_store_memory_gb: 8
    num_gpus: 0"""


def data_input_block(reuse_transformed='Yes'):
    lines = ["data_input:", "  groups:", "    alz:"]
    for p in ALZ_PATHS:
        lines.append(f"    - {p}")
    lines.append("    cntrl:")
    for p in CNTRL_PATHS:
        lines.append(f"    - {p}")
    lines += [
        "  reuse_processed_subjects: 'Yes'",
        "  save_processed_subjects: 'Yes'",
        f"  reuse_transformed: '{reuse_transformed}'",
        "  save_transformed: 'Yes'",
        "  reuse_transformed_across_experiments: 'No'",
        "  reuse_processed_subjects_across_experiments: 'Yes'",
    ]
    return "\n".join(lines)


def lpso_strategy(p_per_group, folds, total_folds=50):
    lines = [
        "data_transformation_strategy:",
        "  strategy: LPSO (Leave-P-Subjects-Out) (inter subject split) - systematic cross-validation",
        "    (recommended for small datasets)",
        f"  lpso_subjects_per_group: {p_per_group}",
        "  uneven_handling: cutoff",
        "  lpso_folds:",
    ]
    for fold in folds:
        lines.append(f"  - - {fold[0]}")
        for s in fold[1:]:
            lines.append(f"    - {s}")
    lines += [
        "  lpso_metadata:",
        f"    total_folds: {total_folds}",
        f"    subjects_per_group: {p_per_group}",
        "    total_subjects: 65",
        "    groups:",
        "    - alz",
        "    - cntrl",
        "    num_groups: 2",
        "    fold_generation_method: random",
        "    random_seed: 42",
        "  use_lpso: true",
        "  leaky_lpso: false",
        "  shuffle_transformed_data: 'Yes'",
    ]
    return "\n".join(lines)


def wc_strategy(seed):
    return f"""\
data_transformation_strategy:
  strategy: Within-subject (intra subject split) train/test split (80/20 per subject)
    - each subject contributes to both train and test
  intra_test_train_split:
    train_ratio: 0.8
    random_seed: {seed}
    split_method: random
  shuffle_transformed_data: 'Yes'"""


def project_block(name, seed, config_name):
    return f"""\
project:
  name: {name}
  output_dir: ./data
  experiment_type: ML Classification
  subjects_or_events: subjects
  deployment_method: Singularity with Slurm
  random_seed: {seed}
  expose_ports: 'No'
  config_name: {config_name}
{SLURM}"""


def build_config(name, seed, config_name, feature_transform, data_input, strategy):
    return "\n".join([
        project_block(name, seed, config_name),
        data_input,
        PREPROCESSING,
        FEATURE_EXTRACTION,
        feature_transform,
        strategy,
        PYSPARK,
        RAY,
        "",
    ])


# ── Generate LPSO configs ──────────────────────────────────────────────────────

lpso_dir = ROOT / "lpso_random_50"

configs_lpso = [
    ("ANOVA_L_6_ad_cntrl_random50", "ANOVA_L_6_ad_cntrl_random50.yaml",
     FEATURE_TRANSFORM_ANOVA, L6_FOLDS, 6),
    ("ANOVA_L_2_ad_cntrl_random50", "ANOVA_L_2_ad_cntrl_random50.yaml",
     FEATURE_TRANSFORM_ANOVA, L2_FOLDS, 2),
    ("PCA_L_6_ad_cntrl_random50", "PCA_L_6_ad_cntrl_random50.yaml",
     FEATURE_TRANSFORM_PCA, L6_FOLDS, 6),
    ("PCA_L_2_ad_cntrl_random50", "PCA_L_2_ad_cntrl_random50.yaml",
     FEATURE_TRANSFORM_PCA, L2_FOLDS, 2),
]

for name, fname, ft, folds, p in configs_lpso:
    content = build_config(
        name=name,
        seed=42,
        config_name=fname,
        feature_transform=ft,
        data_input=data_input_block('Yes'),
        strategy=lpso_strategy(p, folds),
    )
    (lpso_dir / fname).write_text(content)
    print(f"  wrote {lpso_dir / fname}")

# ── Generate W_C configs ───────────────────────────────────────────────────────

for seed in range(42, 52):
    # ANOVA W_C
    name  = f"ANOVA_W_C_ad_cntrl_seed{seed}"
    fname = f"ANOVA_W_C_ad_cntrl_seed{seed}.yaml"
    content = build_config(
        name=name,
        seed=seed,
        config_name=fname,
        feature_transform=FEATURE_TRANSFORM_ANOVA,
        data_input=data_input_block('No'),
        strategy=wc_strategy(seed),
    )
    (ROOT / "anova_w_c" / fname).write_text(content)
    print(f"  wrote anova_w_c/{fname}")

    # PCA W_C
    name  = f"PCA_W_C_ad_cntrl_seed{seed}"
    fname = f"PCA_W_C_ad_cntrl_seed{seed}.yaml"
    content = build_config(
        name=name,
        seed=seed,
        config_name=fname,
        feature_transform=FEATURE_TRANSFORM_PCA,
        data_input=data_input_block('No'),
        strategy=wc_strategy(seed),
    )
    (ROOT / "pca_w_c" / fname).write_text(content)
    print(f"  wrote pca_w_c/{fname}")

print("Done — generated 24 config files.")
