#!/usr/bin/env python
"""
Table A: Within-Subject (80/20, single split) — Best Accuracies (Control)

Shows best accuracy for each transform and task type (Fingerprinting vs Classification).
"""

import json
from pathlib import Path
import statistics

BASE_DIR = Path(__file__).parent

EXPERIMENTS = {
    "PCA_Fingerprinting": {
        "path": BASE_DIR / "grid_12_folds/PCA_W_F-3/ml_results_grid_search",
        "task": "Fingerprinting"
    },
    "PCA_Classification": {
        "path": BASE_DIR / "grid_12_folds/PCA_W_C-3/ml_results_grid_search",
        "task": "Classification"
    },
    "ANOVA_Fingerprinting": {
        "path": BASE_DIR / "grid_12_folds/ANOVA_W_F/ml_results_grid_search",
        "task": "Fingerprinting"
    },
    "ANOVA_Classification": {
        "path": BASE_DIR / "grid_12_folds/ANOVA_W_C/ml_results_grid_search",
        "task": "Classification"
    },
}

def extract_best_accuracy(results_dir):
    """Extract best accuracy and model from within_subject_split."""
    if not results_dir.exists():
        return None, None
    
    best_acc = 0
    best_model = None
    
    model_dirs = [d for d in results_dir.iterdir() 
                  if d.is_dir() and d.name not in ['graphs', 'debug'] and not d.name.startswith('_')]
    
    for model_dir in model_dirs:
        model_name = model_dir.name
        within_dir = model_dir / "within_subject_split"
        
        if not within_dir.exists():
            continue
        
        results_files = list(within_dir.rglob("results.json"))
        for results_file in results_files:
            try:
                with open(results_file, 'r') as f:
                    data = json.load(f)
                accuracy = data.get('test_accuracy') or data.get('test_results', {}).get('accuracy')
                if accuracy and float(accuracy) > best_acc:
                    best_acc = float(accuracy)
                    best_model = model_name
            except:
                continue
    
    return best_acc if best_acc > 0 else None, best_model

def format_model_name(model_name):
    """Format model name for display."""
    # Convert underscores to spaces and handle special cases
    formatted = model_name.replace('_', ' ')
    
    # Special handling for MLP
    if 'MLP' in formatted or 'Neural' in formatted:
        return 'MLP (Neural Network)'
    
    # Keep XGBoost, KNN, SVM as is
    return formatted

def main():
    """Main function."""
    print("=" * 80)
    print("TABLE A: Within-Subject (80/20, single split) — Best Accuracies (Control)")
    print("=" * 80)
    
    results = {}
    
    # Extract results for each experiment
    for exp_name, exp_info in EXPERIMENTS.items():
        transform = exp_name.split('_')[0]
        task = exp_info['task']
        
        print(f"\n📊 Analyzing {transform} - {task}...")
        best_acc, best_model = extract_best_accuracy(exp_info['path'])
        
        if best_acc and best_model:
            key = f"{transform}_{task}"
            results[key] = {
                'transform': transform,
                'task': task,
                'best_accuracy': best_acc,
                'best_model': best_model
            }
            print(f"   ✅ Best: {best_model} ({best_acc:.2%})")
        else:
            print(f"   ⚠️  No results found")
    
    # Create table
    print("\n" + "=" * 80)
    print("TABLE A: Within-Subject (80/20, single split) — Best Accuracies (Control)")
    print("=" * 80)
    
    markdown = """# Table A. Within-Subject (80/20, single split) — Best Accuracies (Control)

| Transform | Task Type | Best Accuracy | Best Model |
|----------|-----------|---------------|------------|
"""
    
    # Order: PCA Fingerprinting, PCA Classification, ANOVA Fingerprinting, ANOVA Classification
    for transform in ["PCA", "ANOVA"]:
        for task in ["Fingerprinting", "Classification"]:
            key = f"{transform}_{task}"
            if key in results:
                r = results[key]
                model_display = format_model_name(r['best_model'])
                markdown += f"| {r['transform']} | {r['task']} | {r['best_accuracy']:.2%} | {model_display} |\n"
    
    markdown += """
---

## Footnote

80/20 within-subject split (train/test from the same person). Features per transform as labeled (PCA or ANOVA → MinMax). Best model = highest test accuracy on the single split.

*Generated by `create_table_a_within_subject_control.py`*
"""
    
    # Save
    output_file = BASE_DIR / "table_a_within_subject_control.md"
    with open(output_file, 'w') as f:
        f.write(markdown)
    
    print("\n" + markdown)
    print(f"\n✅ Saved to: {output_file}")
    
    print("\n" + "=" * 80)
    print("ANALYSIS COMPLETE")
    print("=" * 80)

if __name__ == '__main__':
    main()


