project:
  name: test
  output_dir: ./data
  experiment_type: Classification
  subjects_or_events: subjects
  artifact_removal: ICA
  config_name: config_test_25-07-2025_1144.yaml
  deployment_method: Docker
data_input:
  groups:
    group_1:
    - /Users/user/bigData/ds004504-download/sub-001/eeg/sub-001_task-eyesclosed_eeg.set
    group_2:
    - /Users/user/bigData/ds004504-download/sub-037/eeg/sub-037_task-eyesclosed_eeg.set
  reuse_expanded: 'Yes'
  save_expanded: 'Yes'
preprocessing:
  bands:
    Delta:
    - 0.5
    - 4
    Theta:
    - 4
    - 8
    Alpha:
    - 8
    - 12
    Beta:
    - 12
    - 30
    Gamma:
    - 30
    - 50
  window_size: 3.0
  sliding_window: 0.5
  downsampling: null
feature_extraction:
  method: Welch (default)
  features:
  - Band Power (averaged across all channels/bands)
  - Band Power (per channel, averaged across bands)
  - Band Power (averaged across channels, per band) *(not usually used)
  - Band Power (per channel per band) *recommended
feature_transformation:
  transformations: PCA (retain 95% variance)
  synthetic: None
classification:
  split_method: By subject
pyspark:
  master: '4'
  driver_memory: '6'
  executor_memory: '6'
  executor_cores: '2'
  shuffle_partitions: '8'
