project:
  name: Testx1
  output_dir: data
  experiment_type: Classification
  config_name: config_20250709_154630.yaml
data_input:
  groups:
    group_1:
    - /Users/user/bigData/ds004504-download/sub-001/eeg/sub-001-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-002/eeg/sub-002-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-003/eeg/sub-003-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-004/eeg/sub-004-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-005/eeg/sub-005-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-006/eeg/sub-006-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-007/eeg/sub-007-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-008/eeg/sub-008-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-009/eeg/sub-009-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-010/eeg/sub-010-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-011/eeg/sub-011-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-012/eeg/sub-012-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-013/eeg/sub-013-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-014/eeg/sub-014-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-015/eeg/sub-015-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-016/eeg/sub-016-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-017/eeg/sub-017-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-018/eeg/sub-018-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-019/eeg/sub-019-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-020/eeg/sub-020-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-021/eeg/sub-021-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-022/eeg/sub-022-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-023/eeg/sub-023-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-024/eeg/sub-024-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-025/eeg/sub-025-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-026/eeg/sub-026-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-027/eeg/sub-027-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-028/eeg/sub-028-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-029/eeg/sub-029-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-030/eeg/sub-030-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-031/eeg/sub-031-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-032/eeg/sub-032-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-033/eeg/sub-033-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-034/eeg/sub-034-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-035/eeg/sub-035-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-036/eeg/sub-036-eyesclosed_eeg.set
    group_2:
    - /Users/user/bigData/ds004504-download/sub-037/eeg/sub-037-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-038/eeg/sub-038-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-039/eeg/sub-039-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-040/eeg/sub-040-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-041/eeg/sub-041-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-042/eeg/sub-042-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-043/eeg/sub-043-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-044/eeg/sub-044-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-045/eeg/sub-045-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-046/eeg/sub-046-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-047/eeg/sub-047-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-048/eeg/sub-048-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-049/eeg/sub-049-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-050/eeg/sub-050-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-051/eeg/sub-051-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-052/eeg/sub-052-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-053/eeg/sub-053-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-054/eeg/sub-054-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-055/eeg/sub-055-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-056/eeg/sub-056-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-057/eeg/sub-057-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-058/eeg/sub-058-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-059/eeg/sub-059-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-060/eeg/sub-060-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-061/eeg/sub-061-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-062/eeg/sub-062-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-063/eeg/sub-063-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-064/eeg/sub-064-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-065/eeg/sub-065-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-066/eeg/sub-066-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-067/eeg/sub-067-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-068/eeg/sub-068-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-069/eeg/sub-069-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-070/eeg/sub-070-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-071/eeg/sub-071-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-072/eeg/sub-072-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-073/eeg/sub-073-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-074/eeg/sub-074-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-075/eeg/sub-075-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-076/eeg/sub-076-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-077/eeg/sub-077-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-078/eeg/sub-078-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-079/eeg/sub-079-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-080/eeg/sub-080-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-081/eeg/sub-081-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-082/eeg/sub-082-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-083/eeg/sub-083-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-084/eeg/sub-084-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-085/eeg/sub-085-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-086/eeg/sub-086-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-087/eeg/sub-087-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-088/eeg/sub-088-eyesclosed_eeg.set
  reuse_expanded: 'Yes'
  save_expanded: 'Yes'
preprocessing:
  bands:
  - Delta
  - Theta
  - Alpha
  - Beta
  - Gamma
  downsampling: null
  artifact_removal: None
feature_extraction:
  method: Welch
  features: []
feature_transformation:
  transformations: []
  synthetic: None
classification:
  split_method: By subject
