project:
  name: testx1
  output_dir: ./data
  experiment_type: Classification
  deployment_method: Docker
  config_name: config_testx1_23-07-2025_1346.yaml
pyspark:
  master: '4'
  driver_memory: '6'
  executor_memory: '6'
  executor_cores: '2'
  shuffle_partitions: '8'
data_input:
  groups:
    group_1:
    - /Users/user/bigData/ds004504-download/sub-001/eeg/sub-001_task-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-002/eeg/sub-002_task-eyesclosed_eeg.set
    group_2:
    - /Users/user/bigData/ds004504-download/sub-037/eeg/sub-037_task-eyesclosed_eeg.set
    - /Users/user/bigData/ds004504-download/sub-038/eeg/sub-038_task-eyesclosed_eeg.set
  reuse_expanded: 'Yes'
  save_expanded: 'Yes'
preprocessing:
  bands:
  - Delta
  - Theta
  - Alpha
  - Beta
  - Gamma
  sliding_window: 0.5
  downsampling: null
  artifact_removal: Where noted in the data
feature_extraction:
  method: Welch (default)
  features:
  - Band Power (averaged across all channels/bands)
  - Band Power (per channel, averaged across bands)
  - Band Power (averaged across channels, per band) *(not usually used)
  - Band Power (per channel per band) *recommended
feature_transformation:
  transformations: PCA (retain 95% variance)
  synthetic: None
classification:
  split_method: By subject
  test_split: '2'
